# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpjungle < Formula
  desc "Self-hosted MCP tool registry for private AI agents"
  homepage "https://github.com/duaraghav8/MCPJungle"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/duaraghav8/MCPJungle/releases/download/v0.1.3/MCPJungle_Darwin_x86_64.tar.gz"
      sha256 "0594b7721ff5ba236622ce164a9510ec595ba8458aeb430727db1d8adc5c35b9"

      def install
        bin.install "mcpjungle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/duaraghav8/MCPJungle/releases/download/v0.1.3/MCPJungle_Darwin_arm64.tar.gz"
      sha256 "fedb68aa3c6a98956e689510b15de297895965235552ed7afd2bc73ca4088b70"

      def install
        bin.install "mcpjungle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/duaraghav8/MCPJungle/releases/download/v0.1.3/MCPJungle_Linux_x86_64.tar.gz"
      sha256 "c67b29186bf73e871cd9f6e6691e243a2baac8c42de89ba03dad26b13f01dda2"
      def install
        bin.install "mcpjungle"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/duaraghav8/MCPJungle/releases/download/v0.1.3/MCPJungle_Linux_arm64.tar.gz"
      sha256 "02f8839f56c6239ad66b11e448f467baf1174fb03cdbffcebfac448d30affa84"
      def install
        bin.install "mcpjungle"
      end
    end
  end
end
