# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpjungle < Formula
  desc "Self-hosted MCP tool registry for private AI agents"
  homepage "https://github.com/duaraghav8/MCPJungle"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/duaraghav8/MCPJungle/releases/download/v0.1.6/MCPJungle_Darwin_x86_64.tar.gz"
      sha256 "67de2b5592f3b74c53060253a00c8c75c1bf8facdfba40937da5a61608848c62"

      def install
        bin.install "mcpjungle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/duaraghav8/MCPJungle/releases/download/v0.1.6/MCPJungle_Darwin_arm64.tar.gz"
      sha256 "7998f3284aed9bad7c8f1c9caa3425872e0c29001f1706ffd208cc51eff37b0e"

      def install
        bin.install "mcpjungle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/duaraghav8/MCPJungle/releases/download/v0.1.6/MCPJungle_Linux_x86_64.tar.gz"
      sha256 "2a410a2897ffbaac14c4742bae383b091f25f3bd042f1c2d06eb08b1965a40d6"
      def install
        bin.install "mcpjungle"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/duaraghav8/MCPJungle/releases/download/v0.1.6/MCPJungle_Linux_arm64.tar.gz"
      sha256 "40c6aaa91ac19a51fced9c992a8325f23c8eaa1d48091a2a08b1b58289c8c05d"
      def install
        bin.install "mcpjungle"
      end
    end
  end
end
